markdown: rdiscount
permalink: /:title/
url: http://jimmyyan.github.io
name: jimmy
author: jimmyyan
qq: 185731273
email: jm.y8581@gmail.com
duoshuo: jimmyyan
beian: 
cnzz: 
weibo: 
github: jimmyyan
pygments: true
paginate: 20
truncate: true
about: "jimmyyan's blog"
