markdown: rdiscount
permalink: /:title/
url: http://jimmyyan.github.io
name: jimmyyan
author: jimmyyan
qq: 185731273
email: jm.y8581@gmail.com
beian: 
cnzz: 119959
weibo: 
github: jimmyyan
pygments: true
safe: true
paginate: 20
truncate:true
about: "jimmyan's blog"
